// swift-tools-version: 6.1
//===----------------------------------------------------------------------===//
// This source file is part of github.com/apple/SwiftUsd
//
// Copyright © 2025 Apple Inc. and the SwiftUsd project authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// This file was auto-generated by make-swift-package. Do not edit!

import PackageDescription
import CompilerPluginSupport

let package = Package(
    name: "OpenUSD",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [
        .library(name: "OpenUSD", targets: [
            "_OpenUSD_SwiftBindingHelpers",
            "OpenUSD"
        ]),
        .executable(name: "OpenUSDValidationCatalogTool", targets: [
            "OpenUSDValidationCatalogTool"
        ])
    ],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-syntax.git", "600.0.0-latest"..."603.0.0"),
    ],
    targets: [
        .target(name: "OpenUSD",
                dependencies: [
                    "_OpenUSD_SwiftBindingHelpers",
                    "_OpenUSD_MacroImplementations",
                    .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                    .product(name: "SwiftCompilerPlugin", package: "swift-syntax")
                ],
                path: "swift-package/Sources/OpenUSD",
                swiftSettings: [
                    .interoperabilityMode(.Cxx)
                ]),

        .macro(name: "_OpenUSD_MacroImplementations",
               dependencies: [
                   .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                   .product(name: "SwiftCompilerPlugin", package: "swift-syntax")
               ],
               path: "swift-package/Sources/_OpenUSD_MacroImplementations"),
                
        .target(name: "_OpenUSD_SwiftBindingHelpers",
                dependencies: cppTarget_dependencies(),
                path: "swift-package/Sources/_OpenUSD_SwiftBindingHelpers"),

        .executableTarget(
            name: "OpenUSDValidationCatalogTool",
            dependencies: ["_OpenUSD_SwiftBindingHelpers"],
            path: "swift-package/Sources/OpenUSDValidationCatalogTool",
            swiftSettings: [
                .interoperabilityMode(.Cxx)
            ]
        )
                
    ] + xcframeworkBinaryTargets(),
    cxxLanguageStandard: .gnucxx17
)



// There are a lot of XCFrameworks that need to get wrapped,
// so we list them after the package initializer
func cppTarget_dependencies() -> [Target.Dependency] {
    [
        .target(name: "Alembic", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Iex", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "IlmThread", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Imath", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "MaterialX", condition: .when(platforms: [.iOS, .visionOS])),
        .target(name: "MaterialXCore", condition: .when(platforms: [.macOS])),
        .target(name: "MaterialXFormat", condition: .when(platforms: [.macOS])),
        .target(name: "MaterialXGenGlsl", condition: .when(platforms: [.macOS])),
        .target(name: "MaterialXGenMsl", condition: .when(platforms: [.macOS])),
        .target(name: "MaterialXGenShader", condition: .when(platforms: [.macOS])),
        .target(name: "MaterialXRender", condition: .when(platforms: [.macOS])),
        .target(name: "MaterialXRenderGlsl", condition: .when(platforms: [.macOS])),
        .target(name: "MaterialXRenderHw", condition: .when(platforms: [.macOS])),
        .target(name: "OpenEXR", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "OpenEXRCore", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "OpenEXRUtil", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "OpenVDB", condition: .when(platforms: [.macOS])),
        .target(name: "OsdCPU", condition: .when(platforms: [.macOS, .visionOS])),
        .target(name: "OsdGPU", condition: .when(platforms: [.macOS, .visionOS])),
        .target(name: "TBB", condition: .when(platforms: [.macOS])),
        .target(name: "Usd_Ar", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Arch", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_CameraUtil", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Ef", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Esf", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_EsfUsd", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Exec", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_ExecGeom", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_ExecIr", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_ExecUsd", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Garch", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_GeomUtil", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Gf", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Glf", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Hd", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_HdGp", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_HdMtlx", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_HdSt", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Hdar", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Hdsi", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Hdx", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Hf", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Hgi", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_HgiGL", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_HgiInterop", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_HgiMetal", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Hio", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_HioOpenVDB", condition: .when(platforms: [.macOS])),
        .target(name: "Usd_Js", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Kind", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Pcp", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Pegtl", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Plug", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_PxOsd", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Sdf", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Sdr", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Tf", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Trace", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Ts", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Usd", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdAppUtils", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdBakeMtlx", condition: .when(platforms: [.macOS])),
        .target(name: "Usd_UsdGeom", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdGeomValidators", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdHydra", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdImaging", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdImagingGL", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdLux", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdMedia", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdMtlx", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdPhysics", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdPhysicsValidators", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdProc", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdProcImaging", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdRender", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdRi", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdSemantics", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdShade", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdShadeValidators", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdSkel", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdSkelImaging", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdSkelValidators", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdUI", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdUtils", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdUtilsValidators", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdValidation", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdVol", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_UsdVolImaging", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Vdf", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Vt", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "Usd_Work", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "blosc", condition: .when(platforms: [.macOS])),
        .target(name: "boost_iostreams", condition: .when(platforms: [.macOS])),
        .target(name: "embree4", condition: .when(platforms: [.macOS])),
        .target(name: "hdEmbree", condition: .when(platforms: [.macOS])),
        .target(name: "hdStorm", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "hioAvif", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "hioImageIO", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "hioOpenEXR", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "sdrGlslfx", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "usdAbc", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
        .target(name: "usdShaders", condition: .when(platforms: [.iOS, .macOS, .visionOS])),
    ]
}

func xcframeworkBinaryTargets() -> [Target] {
    [
        .binaryTarget(name: "Alembic", path: "swift-package/Libraries/Alembic.xcframework"),
        .binaryTarget(name: "Iex", path: "swift-package/Libraries/Iex.xcframework"),
        .binaryTarget(name: "IlmThread", path: "swift-package/Libraries/IlmThread.xcframework"),
        .binaryTarget(name: "Imath", path: "swift-package/Libraries/Imath.xcframework"),
        .binaryTarget(name: "MaterialX", path: "swift-package/Libraries/MaterialX.xcframework"),
        .binaryTarget(name: "MaterialXCore", path: "swift-package/Libraries/MaterialXCore.xcframework"),
        .binaryTarget(name: "MaterialXFormat", path: "swift-package/Libraries/MaterialXFormat.xcframework"),
        .binaryTarget(name: "MaterialXGenGlsl", path: "swift-package/Libraries/MaterialXGenGlsl.xcframework"),
        .binaryTarget(name: "MaterialXGenMsl", path: "swift-package/Libraries/MaterialXGenMsl.xcframework"),
        .binaryTarget(name: "MaterialXGenShader", path: "swift-package/Libraries/MaterialXGenShader.xcframework"),
        .binaryTarget(name: "MaterialXRender", path: "swift-package/Libraries/MaterialXRender.xcframework"),
        .binaryTarget(name: "MaterialXRenderGlsl", path: "swift-package/Libraries/MaterialXRenderGlsl.xcframework"),
        .binaryTarget(name: "MaterialXRenderHw", path: "swift-package/Libraries/MaterialXRenderHw.xcframework"),
        .binaryTarget(name: "OpenEXR", path: "swift-package/Libraries/OpenEXR.xcframework"),
        .binaryTarget(name: "OpenEXRCore", path: "swift-package/Libraries/OpenEXRCore.xcframework"),
        .binaryTarget(name: "OpenEXRUtil", path: "swift-package/Libraries/OpenEXRUtil.xcframework"),
        .binaryTarget(name: "OpenVDB", path: "swift-package/Libraries/OpenVDB.xcframework"),
        .binaryTarget(name: "OsdCPU", path: "swift-package/Libraries/OsdCPU.xcframework"),
        .binaryTarget(name: "OsdGPU", path: "swift-package/Libraries/OsdGPU.xcframework"),
        .binaryTarget(name: "TBB", path: "swift-package/Libraries/TBB.xcframework"),
        .binaryTarget(name: "Usd_Ar", path: "swift-package/Libraries/Usd_Ar.xcframework"),
        .binaryTarget(name: "Usd_Arch", path: "swift-package/Libraries/Usd_Arch.xcframework"),
        .binaryTarget(name: "Usd_CameraUtil", path: "swift-package/Libraries/Usd_CameraUtil.xcframework"),
        .binaryTarget(name: "Usd_Ef", path: "swift-package/Libraries/Usd_Ef.xcframework"),
        .binaryTarget(name: "Usd_Esf", path: "swift-package/Libraries/Usd_Esf.xcframework"),
        .binaryTarget(name: "Usd_EsfUsd", path: "swift-package/Libraries/Usd_EsfUsd.xcframework"),
        .binaryTarget(name: "Usd_Exec", path: "swift-package/Libraries/Usd_Exec.xcframework"),
        .binaryTarget(name: "Usd_ExecGeom", path: "swift-package/Libraries/Usd_ExecGeom.xcframework"),
        .binaryTarget(name: "Usd_ExecIr", path: "swift-package/Libraries/Usd_ExecIr.xcframework"),
        .binaryTarget(name: "Usd_ExecUsd", path: "swift-package/Libraries/Usd_ExecUsd.xcframework"),
        .binaryTarget(name: "Usd_Garch", path: "swift-package/Libraries/Usd_Garch.xcframework"),
        .binaryTarget(name: "Usd_GeomUtil", path: "swift-package/Libraries/Usd_GeomUtil.xcframework"),
        .binaryTarget(name: "Usd_Gf", path: "swift-package/Libraries/Usd_Gf.xcframework"),
        .binaryTarget(name: "Usd_Glf", path: "swift-package/Libraries/Usd_Glf.xcframework"),
        .binaryTarget(name: "Usd_Hd", path: "swift-package/Libraries/Usd_Hd.xcframework"),
        .binaryTarget(name: "Usd_HdGp", path: "swift-package/Libraries/Usd_HdGp.xcframework"),
        .binaryTarget(name: "Usd_HdMtlx", path: "swift-package/Libraries/Usd_HdMtlx.xcframework"),
        .binaryTarget(name: "Usd_HdSt", path: "swift-package/Libraries/Usd_HdSt.xcframework"),
        .binaryTarget(name: "Usd_Hdar", path: "swift-package/Libraries/Usd_Hdar.xcframework"),
        .binaryTarget(name: "Usd_Hdsi", path: "swift-package/Libraries/Usd_Hdsi.xcframework"),
        .binaryTarget(name: "Usd_Hdx", path: "swift-package/Libraries/Usd_Hdx.xcframework"),
        .binaryTarget(name: "Usd_Hf", path: "swift-package/Libraries/Usd_Hf.xcframework"),
        .binaryTarget(name: "Usd_Hgi", path: "swift-package/Libraries/Usd_Hgi.xcframework"),
        .binaryTarget(name: "Usd_HgiGL", path: "swift-package/Libraries/Usd_HgiGL.xcframework"),
        .binaryTarget(name: "Usd_HgiInterop", path: "swift-package/Libraries/Usd_HgiInterop.xcframework"),
        .binaryTarget(name: "Usd_HgiMetal", path: "swift-package/Libraries/Usd_HgiMetal.xcframework"),
        .binaryTarget(name: "Usd_Hio", path: "swift-package/Libraries/Usd_Hio.xcframework"),
        .binaryTarget(name: "Usd_HioOpenVDB", path: "swift-package/Libraries/Usd_HioOpenVDB.xcframework"),
        .binaryTarget(name: "Usd_Js", path: "swift-package/Libraries/Usd_Js.xcframework"),
        .binaryTarget(name: "Usd_Kind", path: "swift-package/Libraries/Usd_Kind.xcframework"),
        .binaryTarget(name: "Usd_Pcp", path: "swift-package/Libraries/Usd_Pcp.xcframework"),
        .binaryTarget(name: "Usd_Pegtl", path: "swift-package/Libraries/Usd_Pegtl.xcframework"),
        .binaryTarget(name: "Usd_Plug", path: "swift-package/Libraries/Usd_Plug.xcframework"),
        .binaryTarget(name: "Usd_PxOsd", path: "swift-package/Libraries/Usd_PxOsd.xcframework"),
        .binaryTarget(name: "Usd_Sdf", path: "swift-package/Libraries/Usd_Sdf.xcframework"),
        .binaryTarget(name: "Usd_Sdr", path: "swift-package/Libraries/Usd_Sdr.xcframework"),
        .binaryTarget(name: "Usd_Tf", path: "swift-package/Libraries/Usd_Tf.xcframework"),
        .binaryTarget(name: "Usd_Trace", path: "swift-package/Libraries/Usd_Trace.xcframework"),
        .binaryTarget(name: "Usd_Ts", path: "swift-package/Libraries/Usd_Ts.xcframework"),
        .binaryTarget(name: "Usd_Usd", path: "swift-package/Libraries/Usd_Usd.xcframework"),
        .binaryTarget(name: "Usd_UsdAppUtils", path: "swift-package/Libraries/Usd_UsdAppUtils.xcframework"),
        .binaryTarget(name: "Usd_UsdBakeMtlx", path: "swift-package/Libraries/Usd_UsdBakeMtlx.xcframework"),
        .binaryTarget(name: "Usd_UsdGeom", path: "swift-package/Libraries/Usd_UsdGeom.xcframework"),
        .binaryTarget(name: "Usd_UsdGeomValidators", path: "swift-package/Libraries/Usd_UsdGeomValidators.xcframework"),
        .binaryTarget(name: "Usd_UsdHydra", path: "swift-package/Libraries/Usd_UsdHydra.xcframework"),
        .binaryTarget(name: "Usd_UsdImaging", path: "swift-package/Libraries/Usd_UsdImaging.xcframework"),
        .binaryTarget(name: "Usd_UsdImagingGL", path: "swift-package/Libraries/Usd_UsdImagingGL.xcframework"),
        .binaryTarget(name: "Usd_UsdLux", path: "swift-package/Libraries/Usd_UsdLux.xcframework"),
        .binaryTarget(name: "Usd_UsdMedia", path: "swift-package/Libraries/Usd_UsdMedia.xcframework"),
        .binaryTarget(name: "Usd_UsdMtlx", path: "swift-package/Libraries/Usd_UsdMtlx.xcframework"),
        .binaryTarget(name: "Usd_UsdPhysics", path: "swift-package/Libraries/Usd_UsdPhysics.xcframework"),
        .binaryTarget(name: "Usd_UsdPhysicsValidators", path: "swift-package/Libraries/Usd_UsdPhysicsValidators.xcframework"),
        .binaryTarget(name: "Usd_UsdProc", path: "swift-package/Libraries/Usd_UsdProc.xcframework"),
        .binaryTarget(name: "Usd_UsdProcImaging", path: "swift-package/Libraries/Usd_UsdProcImaging.xcframework"),
        .binaryTarget(name: "Usd_UsdRender", path: "swift-package/Libraries/Usd_UsdRender.xcframework"),
        .binaryTarget(name: "Usd_UsdRi", path: "swift-package/Libraries/Usd_UsdRi.xcframework"),
        .binaryTarget(name: "Usd_UsdSemantics", path: "swift-package/Libraries/Usd_UsdSemantics.xcframework"),
        .binaryTarget(name: "Usd_UsdShade", path: "swift-package/Libraries/Usd_UsdShade.xcframework"),
        .binaryTarget(name: "Usd_UsdShadeValidators", path: "swift-package/Libraries/Usd_UsdShadeValidators.xcframework"),
        .binaryTarget(name: "Usd_UsdSkel", path: "swift-package/Libraries/Usd_UsdSkel.xcframework"),
        .binaryTarget(name: "Usd_UsdSkelImaging", path: "swift-package/Libraries/Usd_UsdSkelImaging.xcframework"),
        .binaryTarget(name: "Usd_UsdSkelValidators", path: "swift-package/Libraries/Usd_UsdSkelValidators.xcframework"),
        .binaryTarget(name: "Usd_UsdUI", path: "swift-package/Libraries/Usd_UsdUI.xcframework"),
        .binaryTarget(name: "Usd_UsdUtils", path: "swift-package/Libraries/Usd_UsdUtils.xcframework"),
        .binaryTarget(name: "Usd_UsdUtilsValidators", path: "swift-package/Libraries/Usd_UsdUtilsValidators.xcframework"),
        .binaryTarget(name: "Usd_UsdValidation", path: "swift-package/Libraries/Usd_UsdValidation.xcframework"),
        .binaryTarget(name: "Usd_UsdVol", path: "swift-package/Libraries/Usd_UsdVol.xcframework"),
        .binaryTarget(name: "Usd_UsdVolImaging", path: "swift-package/Libraries/Usd_UsdVolImaging.xcframework"),
        .binaryTarget(name: "Usd_Vdf", path: "swift-package/Libraries/Usd_Vdf.xcframework"),
        .binaryTarget(name: "Usd_Vt", path: "swift-package/Libraries/Usd_Vt.xcframework"),
        .binaryTarget(name: "Usd_Work", path: "swift-package/Libraries/Usd_Work.xcframework"),
        .binaryTarget(name: "blosc", path: "swift-package/Libraries/blosc.xcframework"),
        .binaryTarget(name: "boost_iostreams", path: "swift-package/Libraries/boost_iostreams.xcframework"),
        .binaryTarget(name: "embree4", path: "swift-package/Libraries/embree4.xcframework"),
        .binaryTarget(name: "hdEmbree", path: "swift-package/Libraries/hdEmbree.xcframework"),
        .binaryTarget(name: "hdStorm", path: "swift-package/Libraries/hdStorm.xcframework"),
        .binaryTarget(name: "hioAvif", path: "swift-package/Libraries/hioAvif.xcframework"),
        .binaryTarget(name: "hioImageIO", path: "swift-package/Libraries/hioImageIO.xcframework"),
        .binaryTarget(name: "hioOpenEXR", path: "swift-package/Libraries/hioOpenEXR.xcframework"),
        .binaryTarget(name: "sdrGlslfx", path: "swift-package/Libraries/sdrGlslfx.xcframework"),
        .binaryTarget(name: "usdAbc", path: "swift-package/Libraries/usdAbc.xcframework"),
        .binaryTarget(name: "usdShaders", path: "swift-package/Libraries/usdShaders.xcframework"),
    ]
}